#!/usr/bin/env python3
"""Write image-production questions.json (45 items)."""
from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "content/modules/image-production/questions.json"

NEEDS_REVIEW = {
    "status": "draft",
    "requiresQualifiedReview": True,
    "aiAssisted": True,
    "history": [
        {
            "at": "2026-10-06",
            "status": "draft",
            "actor": "ai-assisted",
            "kind": "revision",
            "note": "Touches dose, thresholds, or device-specific practice; keep out of verified pools until qualified review.",
        }
    ],
}


def Q(n, oid, fam, diff, stem, choices, correct, explanation, simpler, example, eids, review=None, est=55):
    q = {
        "id": f"q-ip-{n:03d}",
        "revision": 1,
        "objectiveIds": oid if isinstance(oid, list) else [oid],
        "familyId": fam,
        "pool": "practice",
        "difficultyIntent": diff,
        "kind": "single",
        "estSeconds": est,
        "stem": stem,
        "choices": [{"id": k, "text": choices[k][0], "rationale": (choices[k][1] if len(choices[k][1]) >= 10 else choices[k][1] + " This matches the cited teaching point.")} for k in "abcd"],
        "correctChoiceId": correct,
        "explanation": explanation,
        "variants": {"simpler": simpler, "example": example},
        "evidenceIds": eids,
    }
    if review:
        q["review"] = review
    return q


questions = [
    Q(1, "obj-ip-unit-components", "fam-ip-unit-def", "recall",
      "Which assemblage is the minimum MQSA definition of a mammography unit?",
      {
          "a": ("Generator, control, tube housing, beam-limiting device, and supporting structures", "Correct. These are the minimum components in § 900.2(dd)."),
          "b": ("Only a digital detector and a compression paddle", "A detector and paddle alone omit required components."),
          "c": ("Any general radiographic room plus a mammography attachment", "General-purpose systems with attachments are prohibited."),
          "d": ("A mobile coach without an x-ray control", "An x-ray control is required."),
      }, "a",
      "MQSA defines a mammography unit as including at least generator, control, tube housing assembly, beam-limiting device, and supports.",
      "Five parts minimum: make x-rays, control them, house the tube, limit the beam, and support them.",
      "If a schematic omits the beam-limiting device, it is incomplete.",
      ["ev-mqsa-mammography-unit-definition"]),
    Q(2, "obj-ip-unit-components", "fam-ip-prohibited", "understand",
      "A clinic proposes using a general radiographic unit fitted with a mammography compression attachment. Under MQSA, this is:",
      {
          "a": ("Allowed if a medical physicist surveys it annually", "Surveys do not legalize prohibited equipment."),
          "b": ("Allowed for screening but not diagnostic exams", "The prohibition is not limited by exam type."),
          "c": ("Prohibited; mammography must use equipment specifically designed for mammography", "Correct."),
          "d": ("Allowed only with DBT software enabled", "Software does not override the equipment prohibition."),
      }, "c",
      "General-purpose or specially attached non-mammography systems shall not be used for mammography.",
      "No bolting a paddle onto a general room.",
      "Accreditation will not save a prohibited configuration.",
      ["ev-mqsa-prohibited-equipment"]),
    Q(3, "obj-ip-unit-components", "fam-ip-beam-order", "understand",
      "Along the primary beam path, which component sits between the tube housing and the compression paddle?",
      {
          "a": ("Image receptor", "The receptor is beyond the breast."),
          "b": ("Beam-limiting device", "Correct. It shapes the field before the paddle and breast."),
          "c": ("Acquisition workstation", "Displays are not in the beam path."),
          "d": ("PACS archive", "Storage is not in the beam path."),
      }, "b",
      "Order: tube housing → beam-limiting device → paddle → breast → support/receptor.",
      "Shape the beam before it hits the patient.",
      "Collimation problems point to the beam-limiting device.",
      ["ev-mqsa-mammography-unit-definition", "ev-mqsa-compression-device"]),
    Q(4, "obj-ip-unit-components", "fam-ip-tube-role", "recall",
      "Which component produces the x-rays in a mammography unit?",
      {
          "a": ("Beam-limiting device", "It shapes the field."),
          "b": ("Compression paddle", "It compresses tissue."),
          "c": ("Tube housing assembly", "Correct. X-rays are produced in the tube within the housing."),
          "d": ("Image receptor", "It detects remnant radiation."),
      }, "c",
      "The tube housing assembly contains the x-ray tube where electrons strike the anode.",
      "X-rays start in the tube housing.",
      "No exposure? Think generator/control/tube first.",
      ["ev-mqsa-mammography-unit-definition", "ev-ip-brems-characteristic"]),
    Q(5, "obj-ip-kvp-tube", "fam-ip-brems", "recall",
      "Bremsstrahlung x-rays are produced when:",
      {
          "a": ("An outer-shell electron falls without a vacancy being created", "Characteristic emission needs a vacancy."),
          "b": ("Electrons decelerate in the anode", "Correct. Bremsstrahlung means braking radiation."),
          "c": ("Photons scatter from the paddle toward the receptor", "That is not anode production."),
          "d": ("The grid absorbs scatter after the breast", "Grid action is after production."),
      }, "b",
      "OpenStax: deceleration of electrons in the anode produces bremsstrahlung.",
      "Braking radiation = electrons slowing in the anode.",
      "The continuous spectrum under characteristic peaks is bremsstrahlung.",
      ["ev-ip-brems-characteristic"], NEEDS_REVIEW),
    Q(6, "obj-ip-kvp-tube", "fam-ip-characteristic", "understand",
      "Characteristic x-ray energies primarily depend on:",
      {
          "a": ("The patient's breast thickness alone", "Thickness affects attenuation, not anode line energies."),
          "b": ("The electron binding energies of the anode material", "Correct. Energies identify the anode element."),
          "c": ("The matrix size of the digital detector", "Detector sampling is unrelated."),
          "d": ("Whether the grid is in or out", "Grid status does not set characteristic energies."),
      }, "b",
      "Characteristic x-rays are emitted when inner-shell vacancies are filled; energies are characteristic of the anode element.",
      "Anode element → characteristic peaks.",
      "Changing anode material moves the peaks.",
      ["ev-ip-brems-characteristic"], NEEDS_REVIEW),
    Q(7, "obj-ip-kvp-tube", "fam-ip-emax", "apply",
      "Using E_max = qeV, a tube operated at 30 kV can produce photons with a maximum energy of:",
      {
          "a": ("30 eV", "Off by a factor of 1000."),
          "b": ("30 keV", "Correct. kV maps to keV maximum."),
          "c": ("30 MeV", "Far too high for diagnostic tubes."),
          "d": ("Only energies exactly at characteristic peaks", "E_max is the continuum cutoff."),
      }, "b",
      "OpenStax pattern: 100 kV → 100 keV maximum; likewise 30 kV → 30 keV max.",
      "kV number matches keV maximum.",
      "Most photons are below E_max.",
      ["ev-ip-emax-kvp"], NEEDS_REVIEW),
    Q(8, "obj-ip-kvp-tube", "fam-ip-contrast-energy", "understand",
      "Which statement matches OpenStax teaching on x-ray energy and contrast?",
      {
          "a": ("Higher-energy beams always improve soft-tissue contrast", "Higher energy usually reduces contrast."),
          "b": ("Lower-energy x-rays provide better contrast but are attenuated more by thicker material", "Correct."),
          "c": ("Photon energy does not affect penetration", "Penetration rises with energy."),
          "d": ("Soft tissues are easy to separate because absorption differs enormously", "Soft-tissue absorption is similar."),
      }, "b",
      "Low-energy x-rays provide better contrast; higher-energy photons penetrate more; soft-tissue absorption is similar.",
      "Softer beam: more contrast, less punch.",
      "That tension is why mammography technique is specialized.",
      ["ev-ip-energy-penetration-contrast", "ev-ip-breast-soft-tissue-contrast"], NEEDS_REVIEW),
    Q(9, "obj-ip-paddles-grids", "fam-ip-paddle-parallel", "recall",
      "Under MQSA, a flat compression paddle under compression may deflect from parallel by no more than:",
      {
          "a": ("0.1 cm", "Too strict."),
          "b": ("1.0 cm", "Correct."),
          "c": ("2.0 cm", "Not the stated limit."),
          "d": ("10% of SID", "Percent-of-SID language is for alignment tests."),
      }, "b",
      "§ 900.12(b)(8): not more than 1.0 cm from parallel when compression is applied.",
      "One centimeter max.",
      "A clearly wedged paddle fails this expectation.",
      ["ev-mqsa-compression-device"]),
    Q(10, "obj-ip-paddles-grids", "fam-ip-compression-why", "understand",
      "According to NCI, why is the breast pressed between two plates?",
      {
          "a": ("To sterilize the skin", "Not a sterilizing step."),
          "b": ("To help get a better x-ray picture of the inside of the breast", "Correct."),
          "c": ("To permanently flatten fibroglandular tissue", "Compression is temporary."),
          "d": ("To replace the need for labeling", "Labeling remains required."),
      }, "b",
      "NCI: pressing helps get a better x-ray picture of the inside of the breast.",
      "Compression = better picture.",
      "Use that plain sentence with patients.",
      ["ev-ip-nci-compression-purpose"]),
    Q(11, "obj-ip-paddles-grids", "fam-ip-grid-mag", "recall",
      "Systems used for magnification procedures must be able to:",
      {
          "a": ("Operate only with the grid in place", "Opposite of the requirement."),
          "b": ("Operate with the grid removed", "Correct."),
          "c": ("Disable compression entirely", "Compression is still used."),
          "d": ("Remove the beam-limiting device", "Collimation remains necessary."),
      }, "b",
      "MQSA requires magnification systems to operate with the grid removed.",
      "Mag mode: grid out.",
      "Air-gap geometry replaces grid cleanup.",
      ["ev-mqsa-magnification-equipment"]),
    Q(12, "obj-ip-paddles-grids", "fam-ip-paddle-controls", "recall",
      "MQSA compression-device controls must include initial power-driven compression that is:",
      {
          "a": ("Foot-pedal only on the left side of the patient", "Must be hands-free controls operable from both sides."),
          "b": ("Activated from hands-free controls operable from both sides of the patient", "Correct."),
          "c": ("Available only at the acquisition workstation keyboard", "Must be at the unit, both sides."),
          "d": ("Disabled for screening exams", "Compression is used for screening."),
      }, "b",
      "Initial power-driven compression is activated from hands-free controls operable from both sides; fine adjustment also from both sides.",
      "Both sides, hands-free power drive.",
      "You should not need to walk around the gantry to start compression.",
      ["ev-mqsa-compression-device"]),
    Q(13, "obj-ip-geometry", "fam-ip-mag-range", "recall",
      "For systems used for magnification, MQSA requires at least one magnification value in which range?",
      {
          "a": ("1.1 to 1.2", "Too low."),
          "b": ("1.4 to 2.0", "Correct."),
          "c": ("2.5 to 3.0", "Above the stated minimum range."),
          "d": ("Any value chosen by the technologist without a design minimum", "A design minimum range is specified."),
      }, "b",
      "At least one magnification value within 1.4 to 2.0 is required.",
      "Remember 1.4–2.0.",
      "Having only 1.2× available would not meet the requirement.",
      ["ev-mqsa-magnification-equipment"], NEEDS_REVIEW),
    Q(14, "obj-ip-geometry", "fam-ip-oid", "understand",
      "Raising the breast on a magnification platform primarily increases which distance?",
      {
          "a": ("SID only, with OID unchanged", "OID increases when the object moves away from the receptor."),
          "b": ("OID (object-to-image distance)", "Correct. That enlargement geometry creates the air gap."),
          "c": ("Detector pixel pitch", "Pixel pitch is a detector property."),
          "d": ("Paddle deflection limit", "Deflection limit is a paddle design rule."),
      }, "b",
      "Magnification increases OID, enlarging the projection and creating an air gap.",
      "Raise the breast → larger OID.",
      "Contact views keep the breast on the receptor.",
      ["ev-mqsa-magnification-equipment"], NEEDS_REVIEW),
    Q(15, "obj-ip-geometry", "fam-ip-sid-ref", "understand",
      "Why do some MQSA alignment tolerances use \"percent of SID\"?",
      {
          "a": ("Because SID is the reference distance for the system's geometry", "Correct."),
          "b": ("Because SID equals patient dose in mGy", "SID is a length, not a dose."),
          "c": ("Because SID replaces the need for a beam-limiting device", "Collimation is still required."),
          "d": ("Because SID is only defined for CT", "SID is used in mammography QC language."),
      }, "a",
      "Field and paddle alignment limits are expressed relative to SID.",
      "SID is the yardstick for those checks.",
      "Technologists recognize the term; physicists measure the tolerances.",
      ["ev-mqsa-field-alignment"], NEEDS_REVIEW),
    Q(16, "obj-ip-geometry", "fam-ip-air-gap", "understand",
      "In magnification geometry, the air gap's practical role is to:",
      {
          "a": ("Increase scatter reaching the detector", "Air gap reduces scatter acceptance."),
          "b": ("Reduce scatter reaching the detector when the grid is removed", "Correct."),
          "c": ("Eliminate the need for compression", "Compression is still used."),
          "d": ("Convert FFDM into ultrasound", "Unrelated modality."),
      }, "b",
      "With the grid removed, the air gap helps keep scatter from reaching the receptor.",
      "Air gap ≈ scatter control without a grid.",
      "That is why mag mode and grid-out travel together.",
      ["ev-mqsa-magnification-equipment"], NEEDS_REVIEW),
    Q(17, "obj-ip-acquisition-types", "fam-ip-modality-def", "recall",
      "Which list matches MQSA examples of mammographic modalities?",
      {
          "a": ("Ultrasound, MRI, and PET", "Those are not mammographic modalities under § 900.2."),
          "b": ("Screen-film, FFDM, and DBT", "Correct."),
          "c": ("Fluoroscopy, angiography, and tomosynthesis of the chest", "Not breast mammography modalities."),
          "d": ("Only film systems installed before 1999", "Digital modalities are included."),
      }, "b",
      "Examples: screen-film, full-field digital mammography, and digital breast tomosynthesis.",
      "Film, FFDM, DBT.",
      "Modality-specific training hours attach to these categories.",
      ["ev-mqsa-modality-definition"]),
    Q(18, "obj-ip-acquisition-types", "fam-ip-dbt-how", "understand",
      "How does NCI describe the creation of a DBT (3D) image set?",
      {
          "a": ("A single exposure is mathematically stretched into depth", "DBT acquires multiple projections/slices."),
          "b": ("Multiple thin-slice pictures are taken and assembled by software into a 3D picture", "Correct."),
          "c": ("Only ultrasound slices are fused to a 2D mammogram", "That is not DBT."),
          "d": ("Film images are digitized after processing", "That describes historical film digitization, not DBT."),
      }, "b",
      "NCI: multiple thin-slice pictures assembled into a 3D picture by software.",
      "Many slices → 3D volume.",
      "Tube motion during acquisition is the usual hardware picture.",
      ["ev-ip-nci-dbt"]),
    Q(19, "obj-ip-acquisition-types", "fam-ip-dbt-2d", "recall",
      "According to NCI, which statement about DBT and 2D images is accurate?",
      {
          "a": ("DBT never produces 2D images", "NCI says DBT also creates 2D images."),
          "b": ("DBT also creates 2D images like those from standard mammography", "Correct."),
          "c": ("DBT replaces labeling requirements", "Labeling still applies."),
          "d": ("DBT can be performed on general-purpose radiographic rooms", "Equipment must still be mammography systems."),
      }, "b",
      "DBT creates 3D images and also creates 2D images like standard mammography.",
      "DBT still gives you 2D-looking images.",
      "Synthesized 2D is a common related workflow on modern units.",
      ["ev-ip-nci-dbt"]),
    Q(20, "obj-ip-acquisition-types", "fam-ip-dbt-outcome", "understand",
      "NCI states that DBT combined with standard mammography is better at finding tumors than standard mammography alone. What does NCI say about mortality benefit?",
      {
          "a": ("Mortality reduction is already proven to be larger than for 2D alone", "NCI says this is still unknown/being studied."),
          "b": ("It is still unknown whether DBT reduces deaths more than standard mammography alone", "Correct."),
          "c": ("DBT has been proven to increase breast-cancer deaths", "Not what NCI states."),
          "d": ("Mortality questions are irrelevant because DBT uses no radiation", "DBT uses x-rays."),
      }, "b",
      "Detection improvement is described; mortality superiority versus standard mammography alone remains under study (e.g., TMIST).",
      "Finds more tumors ≠ proven life-saving superiority yet.",
      "Be precise with patients and on exams.",
      ["ev-ip-nci-dbt"]),
    Q(21, "obj-ip-receptors-monitors", "fam-ip-workstations", "understand",
      "Which distinction best matches acquisition versus interpretation workstations?",
      {
          "a": ("Acquisition is for technologist image-quality checks; interpretation is for diagnostic review", "Correct."),
          "b": ("Acquisition is only for physicists; interpretation is only for technologists", "Roles are reversed/wrong."),
          "c": ("They are identical in purpose, so QC is unnecessary on one of them", "Both need appropriate QC."),
          "d": ("Interpretation workstations produce the x-ray beam", "Workstations do not produce the beam."),
      }, "a",
      "Technologists use acquisition displays to accept or reject images; interpreting physicians use interpretation displays for diagnosis.",
      "Two jobs, two display contexts.",
      "Do not approve poor images just because a dim screen hides the problem.",
      ["ev-ip-acr-dmqc-link"], NEEDS_REVIEW),
    Q(22, "obj-ip-receptors-monitors", "fam-ip-digital-qc-home", "recall",
      "For FFDM/DBT, MQSA says the facility QA program shall be substantially the same as:",
      {
          "a": ("Any internet blog the lead interpreting physician prefers", "Not acceptable."),
          "b": ("The image receptor manufacturer's recommended program (with the phantom dose ceiling still applying)", "Correct."),
          "c": ("Screen-film darkroom chemistry logs only", "Digital programs are not darkroom chemistry."),
          "d": ("A one-time installation checklist with no ongoing tests", "Ongoing QC is required."),
      }, "b",
      "§ 900.12(e)(6): other modalities follow a program substantially the same as the manufacturer's, with the dose maximum still applying.",
      "Manufacturer/ACR digital QC program, plus dose ceiling.",
      "Mammo links the ACR manual; it does not reprint device steps.",
      ["ev-mqsa-other-modalities-qc", "ev-ip-acr-dmqc-link"], NEEDS_REVIEW),
    Q(23, "obj-ip-receptors-monitors", "fam-ip-receptor-location", "recall",
      "In a digital mammography unit, the image receptor is located:",
      {
          "a": ("Inside the tube housing above the collimator", "The tube produces x-rays; it is not the receptor."),
          "b": ("In the breast support that detects the remnant beam", "Correct."),
          "c": ("Only in the PACS server room", "PACS stores images after acquisition."),
          "d": ("In the technologist's lead apron", "Not a receptor location."),
      }, "b",
      "The receptor sits in the breast support assembly along the beam path after the breast.",
      "Detector under the breast.",
      "Schematics show it as the base under the compressed breast.",
      ["ev-mqsa-mammography-unit-definition"]),
    Q(24, "obj-ip-receptors-monitors", "fam-ip-monitor-qc-limit", "understand",
      "Why does this module avoid listing vendor-specific monitor pass/fail numbers?",
      {
          "a": ("Monitor QC is never performed in mammography", "Monitor QC is part of digital programs."),
          "b": ("Those criteria live in copyrighted/manufacturer QC materials cited link-only, and inventing numbers would be unsupported", "Correct."),
          "c": ("MQSA forbids all monitor testing", "MQSA points to manufacturer programs that include display QC."),
          "d": ("Only film viewboxes matter after 2024", "Digital displays are central."),
      }, "b",
      "Detailed patterns and limits are in the digital QC manual/manufacturer docs; Mammo uses link-only citation.",
      "Know the purpose; look up the numbers in your QC binder.",
      "ACR DMQC manual is the usual pointer.",
      ["ev-ip-acr-dmqc-link", "ev-mqsa-other-modalities-qc"], NEEDS_REVIEW),
    Q(25, "obj-ip-exposure-factors", "fam-ip-post-aec", "recall",
      "After an AEC exposure, MQSA requires the system to indicate:",
      {
          "a": ("Only the patient's age", "Age is not the required display."),
          "b": ("The actual kVp and mAs used", "Correct."),
          "c": ("The interpreting physician's NPI", "Not a technique display requirement."),
          "d": ("The accreditation body's phone number", "Not required on the console."),
      }, "b",
      "Following AEC use, the system shall indicate the actual kVp and mAs used.",
      "Read post-exposure kV and mAs.",
      "Those values help you judge whether exposure makes sense.",
      ["ev-mqsa-technique-display"]),
    Q(26, "obj-ip-exposure-factors", "fam-ip-manual", "recall",
      "Regarding technique selection, MQSA requires that systems:",
      {
          "a": ("Disable manual mAs entirely", "Manual selection must be available."),
          "b": ("Provide manual selection of mAs or mA and/or time", "Correct."),
          "c": ("Allow only automatic kV with no display", "Displays are required; manual mAs must exist."),
          "d": ("Hide focal-spot selection from the operator", "Focal spot must be indicated before exposure."),
      }, "b",
      "Manual selection of mAs (or mA and/or time) must be available.",
      "AEC is common; manual must still exist.",
      "Implants or special cases may need manual control per protocol.",
      ["ev-mqsa-technique-display"]),
    Q(27, "obj-ip-exposure-factors", "fam-ip-energy-direction", "understand",
      "If photon energy increases while other factors are unchanged, which directional effect is best supported by OpenStax?",
      {
          "a": ("Penetration decreases and contrast always increases", "Penetration increases with energy."),
          "b": ("Penetration increases; subject contrast tends to decrease", "Correct."),
          "c": ("Neither penetration nor contrast can change", "Both can change."),
          "d": ("The beam becomes non-ionizing", "Diagnostic x-rays remain ionizing."),
      }, "b",
      "Higher-energy photons penetrate more; lower-energy x-rays provide better contrast.",
      "Harder beam: more punch, usually less contrast.",
      "Do not memorize unsupported universal mammo kV charts here.",
      ["ev-ip-energy-penetration-contrast"], NEEDS_REVIEW),
    Q(28, "obj-ip-exposure-factors", "fam-ip-dx-vs-screen-dose", "understand",
      "NCI states diagnostic mammography dose is higher than screening on the same machines primarily because:",
      {
          "a": ("Diagnostic units use radioactive tracers", "Mammography uses x-rays, not tracers."),
          "b": ("Diagnostic exams require images from more angles", "Correct."),
          "c": ("Screening never uses compression", "Both use compression."),
          "d": ("Diagnostic exams never use AEC", "AEC may still be used."),
      }, "b",
      "Same machines; more angles for diagnostic work → higher dose.",
      "More images, more dose.",
      "Still describe mammography as low-dose overall in patient talk.",
      ["ev-ip-nci-diagnostic-more-images"], NEEDS_REVIEW),
    Q(29, "obj-ip-thickness-target-filter", "fam-ip-preselect", "recall",
      "Before exposure, MQSA requires the system to indicate:",
      {
          "a": ("Selected focal spot and target material", "Correct."),
          "b": ("The patient's BI-RADS assessment", "Assessment is after interpretation."),
          "c": ("The facility's malpractice carrier", "Not a console requirement."),
          "d": ("Only the time of day", "Insufficient."),
      }, "a",
      "Systems indicate selected focal spot and target material before exposure.",
      "Check spot and target before you expose.",
      "After AEC, also read actual kV/mAs.",
      ["ev-mqsa-technique-display"]),
    Q(30, "obj-ip-thickness-target-filter", "fam-ip-filter-role", "understand",
      "Filtration in the x-ray beam is used primarily to:",
      {
          "a": ("Add low-energy photons that never reach the patient", "Filtration removes low-energy photons."),
          "b": ("Remove low-energy photons that would increase patient dose without contributing usefully to the image", "Correct conceptually with bremsstrahlung spectra."),
          "c": ("Replace the need for a beam-limiting device", "Collimation is separate."),
          "d": ("Convert x-rays into ultrasound", "Unrelated."),
      }, "b",
      "The beam includes a spectrum; filtration preferentially removes least-penetrating photons that add dose.",
      "Filter out useless soft photons.",
      "Exact filter materials are unit-specific—read the console/docs.",
      ["ev-ip-brems-characteristic", "ev-ip-energy-penetration-contrast"], NEEDS_REVIEW),
    Q(31, "obj-ip-thickness-target-filter", "fam-ip-thickness-aec", "understand",
      "Why should a technologist notice a sudden large jump in displayed mAs for a thickness that usually needs less?",
      {
          "a": ("Displayed mAs is decorative and never meaningful", "MQSA requires the display so you can evaluate technique."),
          "b": ("It may signal a problem with compression, AEC mode, or setup that needs checking before finishing", "Correct."),
          "c": ("It proves the detector has permanently failed", "One value is a cue, not an automatic failure diagnosis."),
          "d": ("It means labeling can be skipped", "Labeling is independent."),
      }, "b",
      "Post-exposure factors exist so operators can judge whether the exposure makes sense for thickness and mode.",
      "Unexpected mAs → stop and think.",
      "Re-check compression and AEC sensor region.",
      ["ev-mqsa-technique-display", "ev-ip-nci-compression-purpose"], NEEDS_REVIEW),
    Q(32, "obj-ip-thickness-target-filter", "fam-ip-no-fake-chart", "understand",
      "This curriculum refuses to publish a universal \"use target X above Y cm\" chart because:",
      {
          "a": ("Target/filter selection never matters", "It matters, but pairings are device-specific."),
          "b": ("Those switch points are device-specific and unsupported as universal rules without manufacturer/facility sources", "Correct."),
          "c": ("MQSA forbids displaying target material", "MQSA requires indicating target material."),
          "d": ("All units use identical anonymous targets", "Units differ."),
      }, "b",
      "Learn directional physics and your unit's documented chart; do not invent universal switch points.",
      "No fake universal technique chart.",
      "Ask your physicist/preceptor for the local chart.",
      ["ev-mqsa-technique-display", "ev-ip-brems-characteristic"], NEEDS_REVIEW),
    Q(33, "obj-ip-magnification-technique", "fam-ip-mag-changes", "apply",
      "Which set best describes geometric magnification technique changes?",
      {
          "a": ("Large focal spot, grid in, breast on the receptor", "That is contact technique."),
          "b": ("Small focal spot, grid out, increased OID/air gap", "Correct."),
          "c": ("No compression, grid in, large focal spot", "Compression is still used; grid out for mag."),
          "d": ("Remove the receptor and photograph the paddle", "Nonsense."),
      }, "b",
      "Magnification: raise breast (OID/air gap), remove grid, use small focal spot; factor 1.4–2.0 available.",
      "Small spot, grid out, air gap.",
      "PACS zoom is not geometric magnification.",
      ["ev-mqsa-magnification-equipment"], NEEDS_REVIEW),
    Q(34, "obj-ip-magnification-technique", "fam-ip-not-zoom", "understand",
      "Enlarging a contact image on a PACS monitor:",
      {
          "a": ("Fully substitutes for a geometric magnification mammogram", "Display zoom is not acquisition magnification."),
          "b": ("Is not the same as acquiring a geometric magnification view", "Correct."),
          "c": ("Automatically removes scatter as an air gap would", "Zoom does not create an air gap."),
          "d": ("Changes the MQSA magnification design range of the unit", "Display zoom does not change equipment capability."),
      }, "b",
      "Geometric magnification changes OID, grid status, and focal spot; monitor zoom does not.",
      "Zoom ≠ mag view.",
      "If the radiologist asks for mag, change acquisition geometry.",
      ["ev-mqsa-magnification-equipment"], NEEDS_REVIEW),
    Q(35, "obj-ip-magnification-technique", "fam-ip-mag-alara", "apply",
      "A magnification view is requested to characterize calcifications. Which action best fits ALARA?",
      {
          "a": ("Add three extra unrequested mag views \"just in case\" without clinical purpose", "Non-beneficial extras violate ALARA."),
          "b": ("Acquire the indicated magnification images using proper mag technique and avoid non-beneficial extras", "Correct."),
          "c": ("Refuse all magnification because LNT forbids medical imaging", "LNT supports caution, not refusal of indicated imaging."),
          "d": ("Perform magnification on a general radiographic room", "Prohibited equipment."),
      }, "b",
      "ALARA: avoid exposure without direct benefit; indicated problem-solving views are beneficial when used correctly.",
      "Do the needed mag views well; skip souvenir extras.",
      "CDC: even small non-beneficial doses should be avoided.",
      ["ev-ip-cdc-alara", "ev-mqsa-magnification-equipment"], NEEDS_REVIEW),
    Q(36, "obj-ip-magnification-technique", "fam-ip-mag-factor-pick", "recall",
      "A unit offers magnification factors of 1.5 and 1.8. Relative to MQSA's design requirement, this capability is:",
      {
          "a": ("Noncompliant because two factors are offered", "Offering more than one is fine."),
          "b": ("Compliant because at least one value lies between 1.4 and 2.0", "Correct."),
          "c": ("Compliant only if the grid stays in", "Grid must be removable."),
          "d": ("Irrelevant because magnification is unregulated", "MQSA states a range."),
      }, "b",
      "At least one value in 1.4–2.0 satisfies the listed design requirement.",
      "1.5 and 1.8 both sit in range.",
      "Still confirm grid-out operation.",
      ["ev-mqsa-magnification-equipment"]),
    Q(37, "obj-ip-image-quality-attributes", "fam-ip-eight-list", "recall",
      "Which option lists all eight clinical image review attributes?",
      {
          "a": ("Positioning, compression, exposure level, contrast, sharpness, noise, artifacts, examination identification", "Correct."),
          "b": ("kVp, mAs, SID, OID, grid, focal spot, filter, anode", "Those are technique factors, not the eight attributes."),
          "c": ("PPV, recall rate, and cancer detection rate only", "Those are audit metrics."),
          "d": ("Only labeling and dose", "Dose is not one of the eight attributes."),
      }, "a",
      "The eight attributes are positioning, compression, exposure level, contrast, sharpness, noise, artifacts, and examination identification.",
      "Memorize the eight.",
      "Dose is QC/phantom territory, not an attribute scored on the clinical image set.",
      ["ev-mqsa-clinical-image-attributes"]),
    Q(38, "obj-ip-image-quality-attributes", "fam-ip-not-attribute", "understand",
      "Which item is NOT one of the eight clinical image review attributes?",
      {
          "a": ("Sharpness", "Sharpness is one of the eight."),
          "b": ("Artifacts", "Artifacts are one of the eight."),
          "c": ("Patient absorbed dose in mGy", "Correct. Dose is not scored as a clinical image attribute."),
          "d": ("Examination identification", "Labeling is the eighth attribute."),
      }, "c",
      "Dose is controlled through equipment QC; it is not one of the eight visual attributes.",
      "If you cannot see it on the image as an attribute, it is not on the list.",
      "Exposure level (too light/dark) is different from a dose measurement.",
      ["ev-mqsa-clinical-image-attributes"]),
    Q(39, "obj-ip-image-quality-attributes", "fam-ip-ongoing", "recall",
      "Between accreditation clinical image reviews, certified facilities must:",
      {
          "a": ("Ignore image quality until the next 3-year submission", "Ongoing compliance is required."),
          "b": ("Continue producing clinical images that meet their accreditation body's quality standards", "Correct."),
          "c": ("Stop using compression to save time", "Compression remains necessary."),
          "d": ("Disable labeling to reduce artifacts", "Labeling is required and is itself an attribute."),
      }, "b",
      "§ 900.12(i): clinical images must continue to comply with the AB's clinical image quality standards.",
      "Quality is everyday, not only every 3 years.",
      "EQUIP asks how you check yourselves between reviews.",
      ["ev-mqsa-clinical-image-quality-standard", "ev-mqsa-equip"]),
    Q(40, "obj-ip-image-quality-attributes", "fam-ip-artifact-fail", "apply",
      "A technically well-positioned image shows a deodorant speck projected over axillary tissue. Which attribute is most clearly failed?",
      {
          "a": ("Examination identification", "Labeling is not the issue described."),
          "b": ("Artifacts", "Correct. External material obscures/mimics structures."),
          "c": ("Outcomes audit PPV", "Audit metrics are unrelated to this single image defect."),
          "d": ("Modality definition", "Modality definition is not an image attribute."),
      }, "b",
      "Artifacts include external material that obscures or mimics anatomy.",
      "Deodorant → artifact problem.",
      "Prevent with clear pre-exam instructions.",
      ["ev-mqsa-clinical-image-attributes"]),
    Q(41, "obj-pc-typical-dose", "fam-ip-alara-def", "recall",
      "ALARA means:",
      {
          "a": ("As large as regulators allow", "Opposite idea."),
          "b": ("As low as reasonably achievable", "Correct."),
          "c": ("Average lung and rib assessment", "Not a radiation term."),
          "d": ("Automatic lateral and right angulation", "Not a radiation term."),
      }, "b",
      "CDC: ALARA = as low as reasonably achievable.",
      "Keep dose low when you can.",
      "Even small non-beneficial doses should be avoided.",
      ["ev-ip-cdc-alara"]),
    Q(42, "obj-pc-typical-dose", "fam-ip-alara-three", "recall",
      "CDC's three basic ALARA protective measures are:",
      {
          "a": ("Time, distance, and shielding", "Correct."),
          "b": ("kVp, mAs, and grid", "Technique factors, not the ALARA triad."),
          "c": ("PPV, sensitivity, and specificity", "Performance metrics."),
          "d": ("Certification, accreditation, and inspection", "MQSA program features."),
      }, "a",
      "Time, distance, and shielding are the three basic measures.",
      "Less time, more distance, use a barrier.",
      "Technologists stepping behind a barrier is the clinic example.",
      ["ev-ip-cdc-alara", "ev-ip-cdc-tech-barrier"]),
    Q(43, "obj-pc-typical-dose", "fam-ip-lnt", "understand",
      "The NRC's linear no-threshold (LNT) model assumes that:",
      {
          "a": ("Below 100 mSv, radiation is proven to be risk-free", "NRC notes data do not absolutely establish risk there, yet still uses LNT conservatively."),
          "b": ("Any increase in dose, no matter how small, results in an incremental increase in risk", "Correct."),
          "c": ("Only alpha particles can cause cancer", "Many radiation types are implicated at high doses."),
          "d": ("Mammography beams are non-ionizing", "X-rays are ionizing."),
      }, "b",
      "NRC accepts LNT as a conservative model: incremental dose → incremental risk estimate.",
      "LNT = no safe threshold assumed for protection math.",
      "Use it to support careful technique, not to terrify patients.",
      ["ev-ip-nrc-lnt"], NEEDS_REVIEW),
    Q(44, "obj-pc-typical-dose", "fam-ip-nci-low-dose", "recall",
      "NCI describes mammography as an imaging test that uses:",
      {
          "a": ("High-dose therapeutic radiotherapy beams", "Mammography is diagnostic imaging, described as low-dose."),
          "b": ("Low-dose x-rays", "Correct."),
          "c": ("Only magnetic fields", "That describes MRI."),
          "d": ("Ultrasound exclusively", "Mammography uses x-rays."),
      }, "b",
      "NCI: mammography uses low-dose x-rays to create pictures of the breast.",
      "Say \"low-dose x-ray exam\" with patients.",
      "Still practice ALARA.",
      ["ev-ip-nci-mammogram-low-dose"]),
    Q(45, "obj-pc-typical-dose", "fam-ip-dna", "understand",
      "OpenStax locates the key molecular target for ionizing-radiation effects in cells at:",
      {
          "a": ("Keratin in nails only", "Not the key target discussed."),
          "b": ("DNA molecules", "Correct."),
          "c": ("Dietary calcium in calcifications", "Calcifications are imaging findings, not the cellular target."),
          "d": ("Lead in aprons", "Shielding material, not a cellular target."),
      }, "b",
      "Ionizing radiation affects molecules within cells, particularly DNA; it can interfere with reproduction and function.",
      "DNA is the critical target in this teaching.",
      "That is why rapidly dividing cells are especially sensitive.",
      ["ev-ip-ionizing-dna"], NEEDS_REVIEW),
]

assert len(questions) == 45, len(questions)
ids = [q["id"] for q in questions]
assert len(ids) == len(set(ids))
# check questions referenced by lessons exist
for need in [1, 5, 9, 13, 17, 21, 25, 29, 33, 37, 41]:
    assert f"q-ip-{need:03d}" in ids

OUT.write_text(json.dumps({"questions": questions}, indent=2, ensure_ascii=False) + "\n")
print(f"Wrote {len(questions)} questions to {OUT}")
