#!/usr/bin/env python3
"""Generate Stage 2 anatomy-pathology module content. Run once from repo root."""
from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
MOD = ROOT / "content/modules/anatomy-pathology"
EV = ROOT / "content/evidence"
ASSETS = ROOT / "public/assets/anatomy-pathology"

AUTO = {
    "status": "auto_checked",
    "requiresQualifiedReview": False,
    "aiAssisted": True,
    "history": [
        {
            "at": "2026-10-06",
            "status": "draft",
            "actor": "ai-assisted",
            "kind": "revision",
            "note": "AI-assisted draft from retrieved public sources (NCI/SEER, OpenStax, 21 CFR, NCI Dictionary).",
        },
        {
            "at": "2026-10-06",
            "status": "auto_checked",
            "actor": "automation",
            "kind": "automated_validation",
            "note": "Passed repository schema/cross-check validation. Not maintainer source-checked; not clinically reviewed. Beta practice only.",
        },
    ],
}

NEED = {
    **AUTO,
    "requiresQualifiedReview": True,
    "history": [
        AUTO["history"][0]
        | {
            "note": "Touches pathology interpretation, upgrade potential, or ambiguous imaging descriptors; keep out of verified pools until qualified review."
        },
        AUTO["history"][1],
    ],
}


def wjson(path: Path, obj):
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(obj, indent=2, ensure_ascii=False) + "\n")
    print("wrote", path.relative_to(ROOT))


def q(
    id: str,
    objective: str,
    family: str,
    stem: str,
    choices: list[tuple[str, str, str]],
    correct: str,
    explanation: str,
    evidence: list[str],
    *,
    pool: str = "practice",
    difficulty: str = "recall",
    review=None,
    simpler: str | None = None,
    example: str | None = None,
    deeper: str | None = None,
    est: int = 55,
):
    choice_objs = [{"id": cid, "text": text, "rationale": rat} for cid, text, rat in choices]
    variants = {
        "simpler": simpler or explanation[:120],
        "example": example or "Apply the sourced definition to the stem before picking.",
    }
    if deeper:
        variants["deeper"] = deeper
    return {
        "id": id,
        "revision": 1,
        "objectiveIds": [objective],
        "familyId": family,
        "pool": pool,
        "difficultyIntent": difficulty,
        "kind": "single",
        "estSeconds": est,
        "stem": stem,
        "choices": choice_objs,
        "correctChoiceId": correct,
        "explanation": explanation,
        "variants": variants,
        "evidenceIds": evidence,
        "review": review or AUTO,
    }


# --------------------------------------------------------------------------- evidence
evidence = [
    {
        "id": "ev-ap-seer-lobes-ducts",
        "sourceId": "src-nci-seer-breast",
        "locator": "SEER Training — Breast anatomy (updated 2025-01-10)",
        "claim": "Each breast has 15–20 lobes arranged circularly; fat covering the lobes contributes to size/shape; each lobe contains lobules ending in milk-making bulbs; lobes/lobules/bulbs are linked by ducts; breasts rest on pectoralis major and are attached by ligaments.",
        "scope": "Gross breast anatomy for technologist localization and tissue composition context.",
        "excerpt": "The breast is made up of lobes and ducts. Each breast has 15 to 20 sections called lobes, which are arranged in a circular fashion. The fat (subcutaneous adipose tissue) that covers the lobes gives the breast its size and shape. Each lobe has many smaller sections called lobules. Lobules end in dozens of tiny bulbs that can make milk. The lobes, lobules, and bulbs are linked by thin tubes called ducts. … They rest on the major chest muscle, the pectoralis major.",
        "citation": "quoted_public",
        "context": {"modality": [], "jurisdiction": "US"},
    },
    {
        "id": "ev-ap-seer-no-muscle-in-breast",
        "sourceId": "src-nci-seer-breast",
        "locator": "SEER Training — Breast anatomy",
        "claim": "The breast itself has no muscle tissue; a layer of fat surrounds the mammary glands.",
        "scope": "Anatomy clarification for positioning relevance (muscle imaged is underlying pectoralis, not intrinsic breast muscle).",
        "excerpt": "The breast itself has no muscle tissue. A layer of fat surrounds the mammary glands.",
        "citation": "quoted_public",
        "context": {"modality": []},
    },
    {
        "id": "ev-ap-seer-ductal-vs-lobular-origin",
        "sourceId": "src-nci-seer-breast",
        "locator": "SEER Training — Breast anatomy",
        "claim": "Ductal carcinoma refers to cancer that starts in the milk ducts; lobular carcinoma originates in the lobes (lobules).",
        "scope": "Technologist-level pathology origin vocabulary.",
        "excerpt": "Ductal carcinoma refers to cancer that starts in the mild ducts (mammary glands), while lobular carcinoma originates in the lobes (lobules).",
        "citation": "quoted_public",
        "context": {"modality": []},
        "review": NEED,
    },
    {
        "id": "ev-ap-seer-quadrants-clock",
        "sourceId": "src-nci-seer-breast",
        "locator": "SEER Training — Breast anatomy / ICD-O-3 table",
        "claim": "Each breast is divided into four quadrants (upper inner, upper outer, lower inner, lower outer) plus a central portion containing areola and nipple; tumor location is typically described as a clock time. ICD-O includes axillary tail (C506). Overlapping lesions include tumors at 3, 6, 9, or 12 o’clock.",
        "scope": "Localization language; does not alone define left/right clock-to-quadrant hour maps beyond named quadrants.",
        "excerpt": "Each breast is divided into four quadrants-Upper inner, upper outer, lower inner, and lower outer, as well as a central portion that contains the areola and nipple. The location of the tumor in the breast is typically described as specific time on a clock.",
        "citation": "quoted_public",
        "context": {"modality": []},
    },
    {
        "id": "ev-ap-seer-lymph-groups",
        "sourceId": "src-nci-seer-breast",
        "locator": "SEER Training — Breast anatomy, Lymph Nodes",
        "claim": "Regional lymph nodes for breast include axillary levels I–III (including interpectoral/Rotter’s), infraclavicular, internal mammary (parasternal), intramammary, and supraclavicular nodes. A sentinel lymph node is the first node to which cancer cells are most likely to spread from a primary tumor.",
        "scope": "Lymphatic anatomy awareness for technologists; not surgical staging instruction.",
        "excerpt": "Groups of lymph nodes are found near the breast in the axilla (under the arm), above the collarbone, and in the chest. … Per the NCI Dictionary A sentinel lymph node is “defined as the first lymph node to which cancer cells are most likely to spread from a primary tumor.”",
        "citation": "quoted_public",
        "context": {"modality": []},
    },
    {
        "id": "ev-ap-seer-histologies",
        "sourceId": "src-nci-seer-breast-types",
        "locator": "SEER Training — Types of Breast Histologies (updated 2025-01-10)",
        "claim": "DCIS develops in milk ducts (~15–20% of breast cancers in this module’s framing). Invasive ductal carcinoma / carcinoma of no special type accounts for about 70% of breast cancers. Invasive lobular carcinoma originates in milk glands and accounts for about 10–15% of invasive breast cancers. Both ductal and lobular carcinomas can be in situ or invasive.",
        "scope": "Technologist-level histology frequencies from SEER training.",
        "excerpt": "The earliest form of the disease, ductal carcinoma in situ (8500/2), comprises about 15-20% of all breast cancers and develops solely in the milk ducts. … Invasive ductal carcinoma accounts for about 70% of breast cancers. … Invasive lobular carcinoma originates in the milk glands and accounts for 10-15% of invasive breast cancers.",
        "citation": "quoted_public",
        "context": {"modality": []},
        "review": NEED,
    },
    {
        "id": "ev-ap-openstax-structure",
        "sourceId": "src-openstax-anatomy-phys-2e",
        "locator": "Anatomy and Physiology 2e § 28.6 Lactation — Structure of the Lactating Breast",
        "claim": "Non-pregnant/non-lactating breast is mostly adipose and collagenous tissue. Alveoli are lined by milk-secreting cells (lactocytes) surrounded by contractile myoepithelial cells. Clusters of alveoli draining to a common duct are lobules (about 12–20). Milk drains via lactiferous ducts to lactiferous sinuses and nipple pores. Montgomery glands on the areola secrete oil.",
        "scope": "Structural anatomy supporting ductal–lobular vocabulary and myoepithelial role in lactation physiology.",
        "excerpt": "Breast alveoli are balloon-like structures lined with milk-secreting cuboidal cells, or lactocytes, that are surrounded by a net of contractile myoepithelial cells. … Clusters of alveoli that drain to a common duct are called lobules; the lactating female has 12–20 lobules organized radially around the nipple. … The small bumps of the areola … are called Montgomery glands.",
        "citation": "quoted_public",
        "context": {"modality": []},
    },
    {
        "id": "ev-ap-openstax-suspensory",
        "sourceId": "src-openstax-clinical-nursing-breast",
        "locator": "Clinical Nursing Skills § 23.4 / OpenStax A&P key term suspensory ligaments",
        "claim": "Supporting the breasts are bands of connective tissue called suspensory ligaments that connect breast tissue to the dermis of the overlying skin.",
        "scope": "Internal support structures relevant to breast mobility during positioning.",
        "excerpt": "Supporting the breasts are multiple bands of connective tissue called suspensory ligaments that connect the breast tissue to the dermis of the overlying skin.",
        "citation": "quoted_public",
        "context": {"modality": []},
    },
    {
        "id": "ev-ap-nci-dense-definition",
        "sourceId": "src-nci-dense-breasts",
        "locator": "NCI Dense Breasts FAQ — What are dense breasts? (updated 2025-12-02)",
        "claim": "Breasts contain glandular, fibrous connective, and fatty tissue. Density describes their relative amounts on a mammogram. Dense tissue has relatively more glandular/fibrous and less fatty tissue.",
        "scope": "Tissue composition / density concept.",
        "excerpt": "Breasts contain glandular tissue, fibrous connective tissue, and fatty breast tissue. Breast density is a term that describes the relative amount of these different types of breast tissue as seen on a mammogram.",
        "citation": "quoted_public",
        "context": {"modality": ["ffdm", "dbt"]},
    },
    {
        "id": "ev-ap-nci-dense-common",
        "sourceId": "src-nci-dense-breasts",
        "locator": "NCI Dense Breasts FAQ — Are dense breasts common?",
        "claim": "Nearly half of women age 40+ who get mammograms have dense breast tissue.",
        "scope": "Prevalence teaching.",
        "excerpt": "Nearly half of all women who are 40 and older who get mammograms are found to have dense breast tissue.",
        "citation": "quoted_public",
        "context": {"modality": []},
    },
    {
        "id": "ev-ap-nci-dense-not-palpable",
        "sourceId": "src-nci-dense-breasts",
        "locator": "NCI Dense Breasts FAQ — How do I know if I have dense breasts?",
        "claim": "Dense breast tissue cannot be felt on self-exam or clinical exam; only a radiologist reading a mammogram can determine density.",
        "scope": "Technologist communication boundary.",
        "excerpt": "Dense breast tissue cannot be felt by a woman, such as during a breast self-exam, or by her doctor during a clinical breast exam. Only a radiologist looking at a mammogram can tell if a woman has dense breasts.",
        "citation": "quoted_public",
        "context": {"modality": []},
    },
    {
        "id": "ev-ap-nci-dense-four",
        "sourceId": "src-nci-dense-breasts",
        "locator": "NCI Dense Breasts FAQ — How is breast density categorized?",
        "claim": "BI-RADS density categories: entirely fatty (~10%); scattered fibroglandular (~40%); heterogeneously dense (~40%); extremely dense (~10%). Dense on a patient letter means heterogeneously or extremely dense.",
        "scope": "Density category awareness; ACR atlas remains link-only for lexicon detail.",
        "excerpt": "If your mammogram report letter says you have dense breasts, it means that you have either heterogeneously dense breast tissue or extremely dense breast tissue.",
        "citation": "quoted_public",
        "context": {"modality": []},
    },
    {
        "id": "ev-ap-nci-dense-masking-risk",
        "sourceId": "src-nci-dense-breasts",
        "locator": "NCI Dense Breasts FAQ — Does density affect a mammogram? / risk factor",
        "claim": "Dense tissue and some abnormalities both appear white, so mammography is less sensitive in dense breasts. Dense breasts are also an independent risk factor for breast cancer (not a disease).",
        "scope": "Why density matters for imaging and risk counseling handoff.",
        "excerpt": "Dense breast tissue and some abnormal breast changes, such as calcifications and tumors, both appear as white areas in the mammogram, whereas fatty tissue appears as dark areas. … dense breasts are a risk factor for breast cancer.",
        "citation": "quoted_public",
        "context": {"modality": ["ffdm"]},
        "review": NEED,
    },
    {
        "id": "ev-ap-nci-birads-table",
        "sourceId": "src-nci-mammograms",
        "locator": "NCI Mammograms fact sheet — How are mammogram results reported? BI-RADS table (updated 2025-12-02)",
        "claim": "NCI lists BI-RADS categories 0–6 with assessment labels and typical follow-up: 0 additional imaging; 1 negative / continue screening; 2 benign / continue screening; 3 probably benign / 6-month follow-up; 4 suspicious / may require biopsy; 5 highly suggestive / requires biopsy; 6 known biopsy-proven malignancy.",
        "scope": "Assessment awareness for technologists — not teaching independent interpretation of images.",
        "excerpt": "Category 0 Need additional imaging evaluation … Category 3 Probably benign Receive a 6-month follow-up mammogram … Category 4 Suspicious abnormality May require biopsy … Category 5 Highly suggestive of malignancy (cancer) Requires biopsy",
        "citation": "quoted_public",
        "context": {"modality": []},
        "review": NEED,
    },
    {
        "id": "ev-ap-nci-mass-calcs",
        "sourceId": "src-nci-mammograms",
        "locator": "NCI Mammograms — What can a mammogram show?",
        "claim": "Mammograms can show masses, calcifications, and density. Smooth/round/clear-edged lumps are often benign cysts; jagged/irregular features may need more tests. Macrocalcifications are often benign; clustered microcalcifications may suggest DCIS or cancer. Neither calcification type is related to dietary calcium.",
        "scope": "Findings vocabulary at patient/technologist level — not full ACR BI-RADS lexicon descriptors.",
        "excerpt": "A lump that is not cancer often looks smooth and round and has clear, defined edges. … Macrocalcifications look like small white dots on a mammogram. They are often … usually benign. Microcalcifications look like white specks … they may be a sign of DCIS or breast cancer.",
        "citation": "quoted_public",
        "context": {"modality": ["ffdm"]},
        "review": NEED,
    },
    {
        "id": "ev-ap-dict-dcis",
        "sourceId": "src-nci-dictionary",
        "locator": "NCI Dictionary of Cancer Terms — ductal carcinoma in situ (termId 45674)",
        "claim": "DCIS: abnormal cells in the lining of a breast duct that have not spread outside the duct to other breast tissues; may become invasive in some cases; also called intraductal breast carcinoma.",
        "scope": "Malignant/in situ vocabulary.",
        "excerpt": "A condition in which abnormal cells are found in the lining of a breast duct. The abnormal cells have not spread outside the duct to other tissues in the breast.",
        "citation": "quoted_public",
        "context": {"modality": []},
        "review": NEED,
    },
    {
        "id": "ev-ap-dict-idc",
        "sourceId": "src-nci-dictionary",
        "locator": "NCI Dictionary — invasive ductal carcinoma (termId 750209)",
        "claim": "Invasive ductal carcinoma is the most common invasive breast cancer; it begins in duct lining and spreads outside the ducts to surrounding normal tissue and can spread via blood/lymph.",
        "scope": "Malignant vocabulary.",
        "excerpt": "The most common type of invasive breast cancer. It begins in the lining of the milk ducts … and spreads outside the ducts to surrounding normal tissue.",
        "citation": "quoted_public",
        "context": {"modality": []},
        "review": NEED,
    },
    {
        "id": "ev-ap-dict-ilc",
        "sourceId": "src-nci-dictionary",
        "locator": "NCI Dictionary — invasive lobular carcinoma (termId 750211)",
        "claim": "Invasive lobular carcinoma begins in breast lobules (milk glands) and spreads to surrounding normal tissue; can spread via blood/lymph.",
        "scope": "Malignant vocabulary.",
        "excerpt": "A type of invasive breast cancer that begins in the lobules (milk glands) of the breast and spreads to surrounding normal tissue.",
        "citation": "quoted_public",
        "context": {"modality": []},
        "review": NEED,
    },
    {
        "id": "ev-ap-dict-ibc",
        "sourceId": "src-nci-dictionary",
        "locator": "NCI Dictionary — inflammatory breast cancer (termId 45313)",
        "claim": "Inflammatory breast cancer is rare and fast-growing; cancer cells block skin lymph vessels, causing swollen/inflamed appearance; often no palpable lump and may not be seen on mammogram; peau d’orange-like skin changes; usually invasive ductal.",
        "scope": "Malignant vocabulary / why clinical signs matter beyond a lump.",
        "excerpt": "A rare, fast-growing type of breast cancer in which cancer cells block lymph vessels in the skin of the breast, causing the breast to look swollen or inflamed. Inflammatory breast cancer usually does not form a lump that can be felt and may not be seen on a mammogram.",
        "citation": "quoted_public",
        "context": {"modality": []},
        "review": NEED,
    },
    {
        "id": "ev-ap-dict-paget",
        "sourceId": "src-nci-dictionary",
        "locator": "NCI Dictionary — Paget disease of the breast/nipple",
        "claim": "Paget disease of the breast involves nipple and usually areola with skin changes (itching, flaking, discharge); most patients also have DCIS or invasive breast cancer.",
        "scope": "Malignant vocabulary.",
        "excerpt": "A rare type of breast cancer that involves the nipple and, usually, the areola … Most people with Paget disease of the breast also have ductal carcinoma in situ … or invasive breast cancer.",
        "citation": "quoted_public",
        "context": {"modality": []},
        "review": NEED,
    },
    {
        "id": "ev-ap-dict-insitu",
        "sourceId": "src-nci-dictionary",
        "locator": "NCI Dictionary — in situ (termId 638205)",
        "claim": "In situ means in its original place; in carcinoma in situ, abnormal cells have not spread from where they first formed.",
        "scope": "Cytology/behavior vocabulary linking to DCIS/LCIS.",
        "excerpt": "In its original place. For example, in carcinoma in situ, abnormal cells are found only in the place where they first formed. They have not spread.",
        "citation": "quoted_public",
        "context": {"modality": []},
    },
    {
        "id": "ev-ap-dict-lcis",
        "sourceId": "src-nci-dictionary",
        "locator": "NCI Dictionary — lobular carcinoma in situ (termId 46315)",
        "claim": "LCIS: abnormal cells in breast lobules; seldom becomes invasive cancer itself, but increases risk of breast cancer in either breast.",
        "scope": "High-risk / risk-marker vocabulary — not management decisions.",
        "excerpt": "A condition in which abnormal cells are found in the lobules of the breast. This condition seldom becomes invasive cancer. However, having lobular carcinoma in situ in one breast increases the risk of developing breast cancer in either breast.",
        "citation": "quoted_public",
        "context": {"modality": []},
        "review": NEED,
    },
    {
        "id": "ev-ap-dict-adh",
        "sourceId": "src-nci-dictionary",
        "locator": "NCI Dictionary — atypical ductal hyperplasia (termId 638190)",
        "claim": "ADH is a benign condition with increased abnormal-appearing cells in duct linings that increases breast cancer risk.",
        "scope": "High-risk lesion vocabulary.",
        "excerpt": "A benign (not cancer) condition in which there are more cells than normal in the lining of breast ducts and the cells look abnormal under a microscope. Having atypical ductal hyperplasia increases the risk of breast cancer.",
        "citation": "quoted_public",
        "context": {"modality": []},
        "review": NEED,
    },
    {
        "id": "ev-ap-dict-alh",
        "sourceId": "src-nci-dictionary",
        "locator": "NCI Dictionary — atypical lobular hyperplasia (termId 638183)",
        "claim": "ALH is a benign condition with increased abnormal-appearing cells in breast lobules that increases breast cancer risk.",
        "scope": "High-risk lesion vocabulary.",
        "excerpt": "A benign (not cancer) condition in which there are more cells than normal in the breast lobules and the cells look abnormal under a microscope. Having atypical lobular hyperplasia increases the risk of breast cancer.",
        "citation": "quoted_public",
        "context": {"modality": []},
        "review": NEED,
    },
    {
        "id": "ev-ap-dict-radial-scar",
        "sourceId": "src-nci-dictionary",
        "locator": "NCI Dictionary — radial scar (termId 804972)",
        "claim": "Radial scar is a benign hardened tissue area that may look like cancer on a mammogram; biopsy is usually needed to differentiate.",
        "scope": "High-risk / mimic vocabulary — technologist awareness, not image diagnosis.",
        "excerpt": "A benign (not cancer) area of hardened tissue in the breast that looks like a scar when viewed under a microscope. … may look like breast cancer on a mammogram … A biopsy is usually needed to tell the difference between these lesions and breast cancer.",
        "citation": "quoted_public",
        "context": {"modality": []},
        "review": NEED,
    },
    {
        "id": "ev-ap-dict-phyllodes",
        "sourceId": "src-nci-dictionary",
        "locator": "NCI Dictionary — phyllodes tumor (termId 46035)",
        "claim": "Phyllodes tumors are rare connective-tissue tumors that grow quickly; most are benign but some are malignant or borderline; usually surgically removed; can recur.",
        "scope": "High-risk / uncommon tumor vocabulary.",
        "excerpt": "A rare tumor that usually forms in the connective tissue of the breast. Phyllodes tumors tend to grow quickly and get large, but they rarely spread to other parts of the body. Most are benign … but some may be malignant … or borderline.",
        "citation": "quoted_public",
        "context": {"modality": []},
        "review": NEED,
    },
    {
        "id": "ev-ap-dict-fibroadenoma",
        "sourceId": "src-nci-dictionary",
        "locator": "NCI Dictionary — fibroadenoma (termId 523438)",
        "claim": "Fibroadenoma is the most common benign breast tumor (fibrous + glandular); typically painless, mobile, well-defined; most do not increase breast cancer risk.",
        "scope": "Benign conditions vocabulary.",
        "excerpt": "A benign (not cancer) tumor that most often forms in the breast and is made up of fibrous (connective) tissue and glandular tissue. … Fibroadenomas are the most common type of benign breast tumor. … Most fibroadenomas do not increase the risk of breast cancer.",
        "citation": "quoted_public",
        "context": {"modality": []},
        "review": NEED,
    },
    {
        "id": "ev-ap-dict-cyst",
        "sourceId": "src-nci-dictionary",
        "locator": "NCI Dictionary — cyst (termId 46461) + NCI Mammograms mass description",
        "claim": "A cyst is a closed sac-like pocket that may contain fluid/air/pus; most cysts are benign. NCI notes smooth/round/clear-edged lumps are often benign cysts.",
        "scope": "Benign conditions vocabulary.",
        "excerpt": "A closed, sac-like pocket of tissue that can form anywhere in the body. It may be filled with fluid, air, pus, or other material. Most cysts are benign (not cancer).",
        "citation": "quoted_public",
        "context": {"modality": []},
    },
    {
        "id": "ev-ap-dict-lipoma",
        "sourceId": "src-nci-dictionary",
        "locator": "NCI Dictionary — lipoma (termId 454795)",
        "claim": "A lipoma is a benign tumor made of fat cells.",
        "scope": "Benign conditions vocabulary.",
        "excerpt": "A benign (not cancer) tumor made of fat cells.",
        "citation": "quoted_public",
        "context": {"modality": []},
    },
    {
        "id": "ev-ap-dict-papilloma",
        "sourceId": "src-nci-dictionary",
        "locator": "NCI Dictionary — intraductal papilloma (termId 430864)",
        "claim": "Intraductal papilloma is a benign wart-like growth in a milk duct, often near the nipple, and may cause nipple discharge; a single papilloma does not increase breast cancer risk.",
        "scope": "Benign conditions vocabulary.",
        "excerpt": "A benign (not cancer), wart-like growth in a milk duct of the breast. It is usually found close to the nipple and may cause a discharge from the nipple. … Having a single papilloma does not increase the risk of breast cancer.",
        "citation": "quoted_public",
        "context": {"modality": []},
        "review": NEED,
    },
    {
        "id": "ev-ap-dict-fat-necrosis",
        "sourceId": "src-nci-dictionary",
        "locator": "NCI Dictionary — fat necrosis (termId 637593)",
        "claim": "Fat necrosis is a benign condition after injury/surgery/radiation in which fat may be replaced by a cyst or scar that can feel like a firm lump.",
        "scope": "Benign conditions vocabulary.",
        "excerpt": "A benign condition in which fat tissue in the breast or other organs is damaged by injury, surgery, or radiation therapy. The fat tissue in the breast may be replaced by a cyst or by scar tissue, which may feel like a round, firm lump.",
        "citation": "quoted_public",
        "context": {"modality": []},
    },
    {
        "id": "ev-ap-dict-sentinel",
        "sourceId": "src-nci-dictionary",
        "locator": "NCI Dictionary — sentinel lymph node (termId 45876)",
        "claim": "The sentinel lymph node is the first lymph node to which cancer is likely to spread from the primary tumor.",
        "scope": "Lymphatic vocabulary.",
        "excerpt": "The first lymph node to which cancer is likely to spread from the primary tumor.",
        "citation": "quoted_public",
        "context": {"modality": []},
    },
    {
        "id": "ev-ap-dict-areola",
        "sourceId": "src-nci-dictionary",
        "locator": "NCI Dictionary — areola (termId 46525)",
        "claim": "The areola is the dark-colored skin on the breast surrounding the nipple.",
        "scope": "External landmark vocabulary.",
        "excerpt": "The area of dark-colored skin on the breast that surrounds the nipple.",
        "citation": "quoted_public",
        "context": {"modality": []},
    },
    {
        "id": "ev-ap-dict-fibroglandular",
        "sourceId": "src-nci-dictionary",
        "locator": "NCI Dictionary — fibroglandular breast tissue (termId 809580)",
        "claim": "Fibroglandular tissue is fibrous connective tissue plus glandular tissue (ducts and lobules); it often appears dense on a mammogram and may make cancer harder to find.",
        "scope": "Tissue composition vocabulary.",
        "excerpt": "A term used to describe breast tissue that is made up of fibrous connective tissue and glandular tissue (milk ducts and lobules). Fibroglandular breast tissue often appears dense on a mammogram, which may make it harder to find breast cancer or other changes in the breast.",
        "citation": "quoted_public",
        "context": {"modality": []},
    },
    {
        "id": "ev-ap-mqsa-assessment",
        "sourceId": "src-ecfr-21-cfr-900",
        "locator": "21 CFR 900.12(c)(1)(iv)–(v) assessment categories",
        "claim": "MQSA final assessment categories include Negative; Benign; Probably Benign; Suspicious; Highly Suggestive of Malignancy; Known Biopsy-Proven Malignancy; and Post-Procedure Mammogram for Marker Placement, plus incomplete categories.",
        "scope": "Report assessment categories in U.S. regulated mammography.",
        "citation": "link_only",
        "context": {"modality": [], "jurisdiction": "US federal", "effective": "current eCFR"},
    },
    {
        "id": "ev-ap-mqsa-density",
        "sourceId": "src-ecfr-21-cfr-900",
        "locator": "21 CFR 900.12(c) density categories and lay statements (eff. 2024-09-10)",
        "claim": "Reports state one of four density categories (almost entirely fatty; scattered areas of fibroglandular density; heterogeneously dense; extremely dense). Lay summaries map the first two to “not dense” and the last two to “dense.”",
        "scope": "Density reporting / patient notification at technologist awareness level.",
        "citation": "link_only",
        "context": {"modality": [], "jurisdiction": "US federal", "effective": "2024-09-10"},
    },
    {
        "id": "ev-ap-acr-birads-link",
        "sourceId": "src-acr-birads-atlas",
        "locator": "ACR BI-RADS Atlas landing page (link-only)",
        "claim": "Detailed mass shape/margin/density and calcification morphology/distribution lexicon definitions are defined in the commercial ACR BI-RADS Atlas; this module does not redistribute those descriptor definitions.",
        "scope": "Rights boundary for lexicon teaching.",
        "citation": "link_only",
        "context": {"modality": []},
        "review": NEED,
    },
]

for e in evidence:
    e.setdefault("retrievedOn", "2026-10-06")
    e.setdefault("review", AUTO if e["id"] not in {
        # keep NEED where already set
    } else e.get("review", AUTO))
    if "review" not in e:
        e["review"] = AUTO

wjson(
    EV / "anatomy-pathology.json",
    {
        "version": "2026-10-06.1",
        "defaults": {"retrievedOn": "2026-10-06", "review": AUTO},
        "evidence": evidence,
    },
)

print(f"evidence count: {len(evidence)}")
